let students = [
    { id: 1, name: "Jack", course: "React", grade: "A", city: "London" },
    { id: 2, name: "Tim", course: "Node", grade: "A", city: "Paris" },
    { id: 3, name: "Anna", course: "JS", grade: "B", city: "London" },
    { id: 4, name: "Bob", course: "Angular", grade: "B", city: "Mumbai" },
    { id: 5, name: "Mary", course: "React", grade: "A", city: "Tokyo" },
    { id: 6, name: "Steve", course: "React", grade: "B", city: "London" },
    { id: 7, name: "Kathy", course: "Node", grade: "C", city: "Tokyo" },
    { id: 8, name: "Vivian", course: "Node", grade: "D", city: "Mumbai" },
    { id: 9, name: "Edwards", course: "JS", grade: "D", city: "Mumbai" },
    { id: 10, name: "George", course: "JS", grade: "C", city: "Tokyo" },
    { id: 11, name: "Sam", course: "Angular", grade: "B", city: "Paris" },
    { id: 12, name: "Amy", course: "Angular", grade: "A", city: "Paris" },
    { id: 13, name: "Jill", course: "JS", grade: "A", city: "Tokyo" },
    { id: 14, name: "Duke", course: "JS", grade: "B", city: "Mumbai" },
    { id: 15, name: "Anita", course: "JS", grade: "B", city: "Paris" },
    { id: 16, name: "Mike", course: "React", grade: "C", city: "London" },
    { id: 17, name: "Teddy", course: "Node", grade: "C", city: "Tokyo" },
    { id: 18, name: "Charles", course: "JS", grade: "D", city: "Mumbai" },
    { id: 19, name: "Bill", course: "Node", grade: "D", city: "London" },
    { id: 20, name: "Carla", course: "React", grade: "D", city: "Tokyo" },
    { id: 21, name: "Joanna", course: "JS", grade: "A", city: "Paris" },
    { id: 22, name: "Pam", course: "JS", grade: "B", city: "Paris" },
    { id: 23, name: "Timothy", course: "React", grade: "C", city: "London" },
    { id: 24, name: "Albert", course: "Node", grade: "A", city: "Paris" },
    { id: 25, name: "Prince", course: "JS", grade: "B", city: "London" },
    { id: 26, name: "Stephen", course: "Node", grade: "B", city: "Paris" },
    { id: 27, name: "Viktor", course: "React", grade: "A", city: "Tokyo" },
    { id: 28, name: "Heather", course: "Node", grade: "B", city: "London" },
    { id: 29, name: "Diana", course: "Node", grade: "C", city: "Tokyo" },
    { id: 30, name: "Norma", course: "JS", grade: "D", city: "Paris" },
    { id: 31, name: "Barbara", course: "JS", grade: "D", city: "London" },
  ];
  module.exports.studentsData = students;