let students = [
    { name: "Jack", course: "React", grade: "A", city: "London" },
    { name: "Tim", course: "Node", grade: "A", city: "Paris" },
    { name: "Anna", course: "JS", grade: "B", city: "London" },
    { name: "Bob", course: "Angular", grade: "B", city: "Mumbai" },
    { name: "Mary", course: "React", grade: "A", city: "Tokyo" },
    { name: "Steve", course: "React", grade: "B", city: "London" },
    { name: "Kathy", course: "Node", grade: "C", city: "Tokyo" },
    { name: "Vivian", course: "Node", grade: "D", city: "Mumbai" },
    { name: "Edwards", course: "JS", grade: "D", city: "Mumbai" },
    { name: "George", course: "JS", grade: "C", city: "Tokyo" },
    { name: "Sam", course: "Angular", grade: "B", city: "Paris" },
    { name: "Amy", course: "Angular", grade: "A", city: "Paris" },
    { name: "Jill", course: "JS", grade: "A", city: "Tokyo" },
    { name: "Duke", course: "JS", grade: "B", city: "Mumbai" },
    { name: "Anita", course: "JS", grade: "B", city: "Paris" },
    { name: "Mike", course: "React", grade: "C", city: "London" },
    { name: "Teddy", course: "Node", grade: "C", city: "Tokyo" },
    { name: "Charles", course: "JS", grade: "D", city: "Mumbai" },
    { name: "Bill", course: "Node", grade: "D", city: "London" },
    { name: "Carla", course: "React", grade: "D", city: "Tokyo" },
    { name: "Joanna", course: "JS", grade: "A", city: "Paris" },
    { name: "Pam", course: "JS", grade: "B", city: "Paris" },
    { name: "Timothy", course: "React", grade: "C", city: "London" },
    { name: "Albert", course: "Node", grade: "A", city: "Paris" },
    { name: "Prince", course: "JS", grade: "B", city: "London" },
    { name: "Stephen", course: "Node", grade: "B", city: "Paris" },
    { name: "Viktor", course: "React", grade: "A", city: "Tokyo" },
    { name: "Heather", course: "Node", grade: "B", city: "London" },
    { name: "Diana", course: "Node", grade: "C", city: "Tokyo" },
    { name: "Norma", course: "JS", grade: "D", city: "Paris" },
    { name: "Barbara", course: "JS", grade: "D", city: "London" },
  ];
  module.exports.studentsData = students;